import type { Metadata } from "next"
import { Toaster } from "react-hot-toast"

import Header from "@/components/modules/Header"
import Footer from "@/components/modules/Footer"
import "./globals.css"

export const metadata: Metadata = {
  title: "Jobvision Clone",
  description: "Generated by create next app",
}

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <Header />
        {children}
        <Footer />
        <Toaster />
      </body>
    </html>
  )
}
